### ISSUE TITLE
Skip the wrapper-keyword?

### ISSUE THREAD

**Issue by friday** [noam09/ulauncher-gnome-control-center#2]
I just noticed ulauncher plugins supports multiple keywords per plugin. I have submitted a [PR](https://github.com/brpaz/ulauncher-hash/pull/4) to another ulauncher plugin which didn't take advantage of this and used a wrapper keyword. I think a similar change would be an improvement for ulauncher-gnome-control-center. At least I would prefer typing "keyboard" directly and getting a "Keyboard Settings" result, rather than "s keyboard".

Because of https://github.com/Ulauncher/Ulauncher/issues/276 you would still get a space inserted, but I think it would work otherwise. If you agree I could try this in a PR (if you want). If not, I could fork. I just prefer to avoid fragmentation if possible. I also understand this is a "breaking" change and may warrant a new entry to the plugin ecosystem for this reason.

**Comment by noam09** [comment]
Hey @friday, thanks for showing interest in the extension. 

What exactly do you mean by "you would still get a space inserted"? Do you mean users would have to type `keyboard<space>` and not only `keyboard`?

It seems like this could be useful, but I'd have to see it in action to really get a feel for it. Maybe submit a PR so I can try it out locally?

**Comment by friday** [comment]
You can try it here: https://github.com/friday/ulauncher-gnome-settings. When you press enter or "alt + letter" to open the setting your input is replaced with the keyword followed by a space character as mentioned, but only very briefly until the Ulauncher widget closes. The space character turned out to be a very minor problem and I didn't even mention it as a caveat, but there are a couple of other ones.

It's not a fork of this repo. If anything, it borrows from the hash extension PR. Your code is more complex and I only needed ~30 loc to make this work. Also, I thought since it both uses an experimental workaround and behaves differently from your extension, it may make sense to make it a new project.

Let me know if you want it though, and preferably what you think.

**Comment by friday** [comment]
I just published my alternative, and have commented about the differences on both extension pages.
* https://ext.ulauncher.io/-/github-friday-ulauncher-gnome-settings
* https://ext.ulauncher.io/-/github-noam09-ulauncher-gnome-control-center

So I'm closing this issue. Implementing this suggestion is a complete rewrite, and wouldn't make much sense any more. We can coexist :+1:

(Feel free to reopen if you disagree of course)

**Comment by noam09** [comment]
Sounds good to me (:
